# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openweather.models.data25_weather_get200_response_main import Data25WeatherGet200ResponseMain
from openweather.models.data25_weather_get200_response_weather_inner import Data25WeatherGet200ResponseWeatherInner
from typing import Optional, Set
from typing_extensions import Self

class Data25ForecastGet200ResponseListInner(BaseModel):
    """
    Data25ForecastGet200ResponseListInner
    """ # noqa: E501
    dt_txt: Optional[StrictStr] = None
    main: Optional[Data25WeatherGet200ResponseMain] = None
    weather: Optional[List[Data25WeatherGet200ResponseWeatherInner]] = None
    __properties: ClassVar[List[str]] = ["dt_txt", "main", "weather"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Data25ForecastGet200ResponseListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of main
        if self.main:
            _dict['main'] = self.main.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in weather (list)
        _items = []
        if self.weather:
            for _item_weather in self.weather:
                if _item_weather:
                    _items.append(_item_weather.to_dict())
            _dict['weather'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Data25ForecastGet200ResponseListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dt_txt": obj.get("dt_txt"),
            "main": Data25WeatherGet200ResponseMain.from_dict(obj["main"]) if obj.get("main") is not None else None,
            "weather": [Data25WeatherGet200ResponseWeatherInner.from_dict(_item) for _item in obj["weather"]] if obj.get("weather") is not None else None
        })
        return _obj


