# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openweather.models.data25_air_pollution_get200_response_list_inner_main import Data25AirPollutionGet200ResponseListInnerMain

class TestData25AirPollutionGet200ResponseListInnerMain(unittest.TestCase):
    """Data25AirPollutionGet200ResponseListInnerMain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data25AirPollutionGet200ResponseListInnerMain:
        """Test Data25AirPollutionGet200ResponseListInnerMain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data25AirPollutionGet200ResponseListInnerMain`
        """
        model = Data25AirPollutionGet200ResponseListInnerMain()
        if include_optional:
            return Data25AirPollutionGet200ResponseListInnerMain(
                aqi = 56
            )
        else:
            return Data25AirPollutionGet200ResponseListInnerMain(
        )
        """

    def testData25AirPollutionGet200ResponseListInnerMain(self):
        """Test Data25AirPollutionGet200ResponseListInnerMain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
