# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openweather.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_data25_air_pollution_get(self) -> None:
        """Test case for data25_air_pollution_get

        Get air quality data
        """
        pass

    def test_data25_forecast_get(self) -> None:
        """Test case for data25_forecast_get

        Get 5-day/3-hour weather forecast
        """
        pass

    def test_data25_weather_get(self) -> None:
        """Test case for data25_weather_get

        Get current weather data for a city
        """
        pass

    def test_geo10_direct_get(self) -> None:
        """Test case for geo10_direct_get

        Geocode a location
        """
        pass


if __name__ == '__main__':
    unittest.main()
