# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openweather.models.data25_weather_get200_response_weather_inner import Data25WeatherGet200ResponseWeatherInner

class TestData25WeatherGet200ResponseWeatherInner(unittest.TestCase):
    """Data25WeatherGet200ResponseWeatherInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data25WeatherGet200ResponseWeatherInner:
        """Test Data25WeatherGet200ResponseWeatherInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data25WeatherGet200ResponseWeatherInner`
        """
        model = Data25WeatherGet200ResponseWeatherInner()
        if include_optional:
            return Data25WeatherGet200ResponseWeatherInner(
                description = '',
                main = ''
            )
        else:
            return Data25WeatherGet200ResponseWeatherInner(
        )
        """

    def testData25WeatherGet200ResponseWeatherInner(self):
        """Test Data25WeatherGet200ResponseWeatherInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
