# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openweather.models.data25_weather_get200_response_main import Data25WeatherGet200ResponseMain

class TestData25WeatherGet200ResponseMain(unittest.TestCase):
    """Data25WeatherGet200ResponseMain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Data25WeatherGet200ResponseMain:
        """Test Data25WeatherGet200ResponseMain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Data25WeatherGet200ResponseMain`
        """
        model = Data25WeatherGet200ResponseMain()
        if include_optional:
            return Data25WeatherGet200ResponseMain(
                temp = 1.337,
                feels_like = 1.337,
                humidity = 1.337
            )
        else:
            return Data25WeatherGet200ResponseMain(
        )
        """

    def testData25WeatherGet200ResponseMain(self):
        """Test Data25WeatherGet200ResponseMain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
