# coding: utf-8

"""
    OpenWeather Proxy API

    API for fetching weather, air quality, and geocoding data from OpenWeatherMap.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openweather.models.geo10_direct_get200_response_inner import Geo10DirectGet200ResponseInner

class TestGeo10DirectGet200ResponseInner(unittest.TestCase):
    """Geo10DirectGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Geo10DirectGet200ResponseInner:
        """Test Geo10DirectGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Geo10DirectGet200ResponseInner`
        """
        model = Geo10DirectGet200ResponseInner()
        if include_optional:
            return Geo10DirectGet200ResponseInner(
                name = '',
                local_names = {
                    'key' : ''
                    },
                lat = 1.337,
                lon = 1.337,
                country = '',
                state = ''
            )
        else:
            return Geo10DirectGet200ResponseInner(
        )
        """

    def testGeo10DirectGet200ResponseInner(self):
        """Test Geo10DirectGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
