# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import spec_pb2 as spec__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeatherAdvisoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAirQuality = channel.unary_unary(
                '/WeatherAdvisory.WeatherAdvisory/GetAirQuality',
                request_serializer=spec__pb2.AirQualityRequest.SerializeToString,
                response_deserializer=spec__pb2.AirQualityResponse.FromString,
                _registered_method=True)
        self.GetWeather = channel.unary_unary(
                '/WeatherAdvisory.WeatherAdvisory/GetWeather',
                request_serializer=spec__pb2.WeatherRequest.SerializeToString,
                response_deserializer=spec__pb2.WeatherResponse.FromString,
                _registered_method=True)
        self.GetTravelRecommendation = channel.unary_unary(
                '/WeatherAdvisory.WeatherAdvisory/GetTravelRecommendation',
                request_serializer=spec__pb2.TravelRequest.SerializeToString,
                response_deserializer=spec__pb2.TravelRecommendationResponse.FromString,
                _registered_method=True)


class WeatherAdvisoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAirQuality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTravelRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherAdvisoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAirQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirQuality,
                    request_deserializer=spec__pb2.AirQualityRequest.FromString,
                    response_serializer=spec__pb2.AirQualityResponse.SerializeToString,
            ),
            'GetWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeather,
                    request_deserializer=spec__pb2.WeatherRequest.FromString,
                    response_serializer=spec__pb2.WeatherResponse.SerializeToString,
            ),
            'GetTravelRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTravelRecommendation,
                    request_deserializer=spec__pb2.TravelRequest.FromString,
                    response_serializer=spec__pb2.TravelRecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WeatherAdvisory.WeatherAdvisory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WeatherAdvisory.WeatherAdvisory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherAdvisory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAirQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherAdvisory.WeatherAdvisory/GetAirQuality',
            spec__pb2.AirQualityRequest.SerializeToString,
            spec__pb2.AirQualityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherAdvisory.WeatherAdvisory/GetWeather',
            spec__pb2.WeatherRequest.SerializeToString,
            spec__pb2.WeatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTravelRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WeatherAdvisory.WeatherAdvisory/GetTravelRecommendation',
            spec__pb2.TravelRequest.SerializeToString,
            spec__pb2.TravelRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
