# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspec.proto\x12\x0fWeatherAdvisory\"!\n\x11\x41irQualityRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"H\n\x12\x41irQualityResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0b\x61ir_quality\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1e\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"I\n\x0fWeatherResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x1d\n\rTravelRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"D\n\x1cTravelRecommendationResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x16\n\x0erecommendation\x18\x02 \x01(\t2\xa6\x02\n\x0fWeatherAdvisory\x12X\n\rGetAirQuality\x12\".WeatherAdvisory.AirQualityRequest\x1a#.WeatherAdvisory.AirQualityResponse\x12O\n\nGetWeather\x12\x1f.WeatherAdvisory.WeatherRequest\x1a .WeatherAdvisory.WeatherResponse\x12h\n\x17GetTravelRecommendation\x12\x1e.WeatherAdvisory.TravelRequest\x1a-.WeatherAdvisory.TravelRecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRQUALITYREQUEST']._serialized_start=31
  _globals['_AIRQUALITYREQUEST']._serialized_end=64
  _globals['_AIRQUALITYRESPONSE']._serialized_start=66
  _globals['_AIRQUALITYRESPONSE']._serialized_end=138
  _globals['_WEATHERREQUEST']._serialized_start=140
  _globals['_WEATHERREQUEST']._serialized_end=170
  _globals['_WEATHERRESPONSE']._serialized_start=172
  _globals['_WEATHERRESPONSE']._serialized_end=245
  _globals['_TRAVELREQUEST']._serialized_start=247
  _globals['_TRAVELREQUEST']._serialized_end=276
  _globals['_TRAVELRECOMMENDATIONRESPONSE']._serialized_start=278
  _globals['_TRAVELRECOMMENDATIONRESPONSE']._serialized_end=346
  _globals['_WEATHERADVISORY']._serialized_start=349
  _globals['_WEATHERADVISORY']._serialized_end=643
# @@protoc_insertion_point(module_scope)
